# Generated by Django 5.0.7 on 2024-07-15 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название категории')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Жанр')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'жанры',
            },
        ),
        migrations.CreateModel(
            name='NewsletterEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='mail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='Название фильма')),
                ('slogan', models.CharField(max_length=260, verbose_name='Слоган')),
                ('country', models.CharField(max_length=70, verbose_name='Страна')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год выпуска')),
                ('producer', models.CharField(max_length=100, verbose_name='Режиссер')),
                ('premier_date', models.DateField(verbose_name='Дата выхода')),
                ('slug', models.SlugField()),
                ('budget', models.PositiveBigIntegerField(verbose_name='Бюджет фильма')),
                ('fees_usa', models.PositiveBigIntegerField(verbose_name='Сборы в США')),
                ('fees_world', models.PositiveBigIntegerField(verbose_name='Сборы в мире')),
                ('poster', models.ImageField(upload_to='previews/', verbose_name='Постер')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/videos/', verbose_name='Видео')),
                ('rating', models.FloatField(default=0.0, verbose_name='Рейтинг фильма')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='website.category', verbose_name='Категория фильма')),
                ('genre', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='genre', to='website.genre')),
            ],
            options={
                'verbose_name': 'фильм',
                'verbose_name_plural': 'фильмы',
            },
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=225, verbose_name='актер')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='website.movie', verbose_name='актеры')),
            ],
            options={
                'verbose_name': 'актер',
                'verbose_name_plural': 'актеры',
            },
        ),
        migrations.CreateModel(
            name='MovieGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery', verbose_name='Галлерея')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='website.movie')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
    ]
