# Generated by Django 5.0.7 on 2024-07-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_moviegallery_options_movie_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
