# Generated by Django 5.0.7 on 2024-08-07 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.reviews', verbose_name='Родитель'),
        ),
    ]
