# Generated by Django 5.0.7 on 2024-08-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_reviews_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
        migrations.AddField(
            model_name='reviews',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Сообщение'),
        ),
    ]
