# Generated by Django 5.0.6 on 2024-08-19 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_movies_reviews_movie_remove_reviews_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='website.movie', verbose_name='Фильм'),
        ),
    ]
